# Generated by Django 4.2 on 2023-04-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
