# Generated by Django 4.2 on 2023-04-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_review_title2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
